---
info:
  component: WB3 K8s | Spring Cloud - Configuration Server
server:
  port: ${SERVER-PORT}
spring:
  application:
    name: ${SPRING-APPLICATION-NAME}
  cloud:
    config:
      server:
        encrypt:
          enabled: ${SPRING-CLOUD-CONFIG-SERVER-ENCRYPT-ENABLED}
        git:
          uri: ${SPRING-CLOUD-CONFIG-SERVER-GIT-URI}
          search-paths:
            - '*' # Search any directory in git repo with '*'; does not limit you to specific directories